build_type: node
static_code_analysis: sonar

branches: 
- type: feature
  build: true
  unit_tests: true
  code_analysis: false
  store_artifact: true

- type: develop
  build: true
  unit_tests: true
  code_analysis: true
  store_artifact: true