name: Handle Node build actions
description: The action will handle all Node build related actions.
inputs:
  node-version:
    description: NodeJS version
    default: 18.20.3
runs:
  using: composite
  steps:
    - name: Node version display
      run: echo "${{ inputs.node-version }}"
      bash: shell
    - name: setup node
      if: inputs.node-version != '18.20.3'
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}

       