name: Handle Node build actions
description: The action will handle all Node build related actions.
inputs:
  node_version:
    description: NodeJS version
    default: 18.20.3
  static_code_analysis:
    description: Tool to be used for static code analysis like sonar, lint.
    default: lint
  build:
    description: true if build action needs to be performed.
  unit_test:
    description: true if unit test action needs to be performed.
  code_analysis:
    description: true if static code analysis action needs to be performed.
  store_artifact:
    description: true to store the artifacts.

default:
  shell: bash

runs:
  using: composite
  steps:   
    - name: print input envs
      run: |
        echo "${{inputs.build}}"
        echo "${{inputs.store_artifact}}"
      shell: bash
    - name: Setup Node
      if: inputs.node-version != '18.20.3'
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
    - name: Build Node Application
      run: |
        npm ci
        npm run build
        ls
      shell: bash
    - name: Execute Unitetests
      run: npm run test
      shell: bash
    - name: Perform ESLint
      if: inputs.static_code_analysis == 'lint'
      run: npm run lint
      shell: bash
    - name: Perform Sonar Analysis
      if: inputs.static_code_analysis == 'sonar'
      run: echo "Sonar analysis..."
      shell: bash

       