name: Handle Node build actions
description: The action will handle all Node build related actions.
inputs:
  node-version:
    description: NodeJS version
    default: 18.20.3
runs:
  using: composite
  steps:    
    - name: Setup Node
      if: inputs.node-version != '18.20.3'
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
    - name: Build Node Application
      run: |
        npm ci
        npm run build
        ls

       