name: Github Actions
on: 
  push:
  workflow_dispatch:

jobs:
  read_config_file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: read_yaml_file
        uses: actions-tools/yaml-outputs@v2
        id: read_action
        with:
            file-path: "${{ github.workspace }}/config.yaml"
            separator: '.'
      - name: print configs
        run: echo "${{env.static_code_analysis}}"
      - name: perform build
        uses: ./.github/actions/builds/node
        with:
          static_code_analysis = "${{env.static_code_analysis}}"

