name: Github Actions
on: 
  push:
  workflow_dispatch:
jobs:
  Node-Express-App:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Execute Build
        uses: ./.github/actions/builds