name: Github Actions
on: 
  push:
  workflow_dispatch:

jobs:
  read_config_file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get branch name from ref
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch
      - name: read_yaml_file
        uses: ./.github/actions/read_yaml
        id: read_action
        with:
            branch-name: ${{steps.extract_branch.outputs.branch}}
      - name: print configs
        run: |
          echo "${{env}}"
          echo "${{steps.read_action.outputs.build_type}}"

      # - name: perform build
      #   uses: ./.github/actions/builds/node
      #   with:
      #     static_code_analysis: ${{env.static_code_analysis}}

