name: Github Actions
on: 
  push:
  workflow_dispatch:

jobs:
  read_config_file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Print vars
        run: |
          echo "${{github.workspace}}"
          pwd
          ls
      - name: read_yaml_file
        uses: actions-tools/yaml-outputs@v2
        id: read_action
        with:
            file-path: "${{ github.workspace }}/config.yaml"
            separator: '.'
      - name: print configs
        run: |
          echo "${{steps.read_action.outputs}}"
          echo "${{env.static_code_analysis}}"
          env

